stages:
  - build
  - deploy

build: 
  stage: build
  script:
    - export GOPATH=$(pwd)/GO_PATH_FOLDER 
    - GO_PROJECT_PATH=$(go-prepare-folder) 
    - cd GO_PROJECT_PATH
    - glide install
    - cd "$GOPATH/..""
    - go build $GO_PROJECT_PATH/cmd/carthage_cache.go
  tags:
    - go
  artifacts:
    expire_in: 1 day
    paths:
      - carthage_cache
  only:
    - master

deploy:
  stage: deploy
  script:
    - scp carthage_cache gitlab-ci@buildben.io:/var/www/utils/carthage_cache
  only:
    - master